name = "GasTranSim"
uuid = "69f9d653-1b8b-4f14-83cd-52913e0d1f1c"
authors = ["Shriram Srinivasan and Kaarthik Sundar"]
version = "0.1.0"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
Dierckx = "~0.4, ~0.5"
JSON = "~0.18, ~0.19, ~0.20, ~0.21"
ProgressMeter = ">= 1.6"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
